### ISSUE TITLE
Error cast from void*’ to ‘int’ loses precision in OpenGL Test

### ISSUE THREAD

**Issue by lukaszml** [oxygine/oxygine-framework#95]
Problem with compile on Ubuntu 'gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) '
```
oxygine/oxygine-framework/examples/Demo/src/TestOpenGL.h:95:63: error: cast from ‘oxygine::nativeTextureHandle {aka void*}’ to ‘int’ loses precision [-fpermissive]
         int texture = (int)frame.getDiffuse().base->getHandle();
```

Solution:
`intptr_t texture = reinterpret_cast<intptr_t>(frame.getDiffuse().base->getHandle());`

 Casting to intptr_t type. It's an int type guaranteed to be big enough to contain a handle.

EDIT. same problem on mac and ios

**Comment by jordan-woyak** [comment]
A cast wouldn't be needed if nativeTextureHandle was a typedef of GLuint in the first place.
I don't know why NativeTextureGLES::_id is a size_t instead of a GLuint as well.

**Comment by frankinshtein** [comment]
fixed.
Handle is not "int32" because in future it could be used for example with d3d where texture handle is pointer

**Comment by lukaszml** [comment]
Are you planning add directx support in future :) ? maybe from 9.0 ?

**Comment by frankinshtein** [comment]
yes, why not?
